### ISSUE TITLE
MongoSession - Cannot access a disposed object.

### ISSUE THREAD

**Issue by BobLd** [BobLd/lean-monitor-2#7]
Try a mongo session that fails, and try again

```
System.Exception
  HResult=0x80131500
  Message=MongoSession.LoadRecentData
  Source=Panoptes.Model.MongoDB
  StackTrace:
   at Panoptes.Model.MongoDB.Sessions.MongoSession.<LoadRecentDataAsync>d__13.MoveNext() in C:\...\Panoptes.Model.MongoDB\Sessions\MongoSession.cs:line 188
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Panoptes.SessionService.<OpenSessionAsync>d__25.MoveNext() in C:\...\Panoptes\SessionService.cs:line 367

  This exception was originally thrown at this call stack:
    MongoDB.Driver.Core.Clusters.Cluster.ThrowIfDisposed()
    MongoDB.Driver.Core.Clusters.Cluster.ThrowIfDisposedOrNotOpen()
    MongoDB.Driver.Core.Clusters.Cluster.SelectServerAsync(MongoDB.Driver.Core.Clusters.ServerSelectors.IServerSelector, System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
    MongoDB.Driver.MongoClient.AreSessionsSupportedAfterServerSelectionAsync(System.Threading.CancellationToken)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]

Inner Exception 1:
ObjectDisposedException: Cannot access a disposed object.
ObjectDisposed_ObjectName_Name
```

**Comment by tjitra** [comment]
hello can any one tell me what is mongodb used for, is any sample mongo db data? or any tutorial can i read? thankyou
